# Generated by Django 4.0 on 2022-01-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('slno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Contact', models.IntegerField(unique=True)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Suggestion', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Forms',
                'verbose_name_plural': 'Formss',
            },
        ),
    ]
