# Generated by Django 4.0 on 2022-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femail', 'Femail'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
            options={
                'verbose_name': 'EmployeeDetails',
                'verbose_name_plural': 'EmployeeDetailss',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
